
import type { Job, User } from './types';

export const JOBS: Job[] = [
  {
    id: 1,
    title: 'Frontend Engineer',
    company: 'Innovate Inc.',
    logo: 'https://picsum.photos/seed/Innovate/100/100',
    location: 'San Francisco, CA',
    salary: '$120,000 - $160,000',
    description: 'We are looking for a passionate Frontend Engineer to join our team. You will be responsible for building the next generation of our user-facing products.',
    responsibilities: [
      'Develop new user-facing features using React.js',
      'Build reusable components and front-end libraries for future use',
      'Translate designs and wireframes into high-quality code',
      'Optimize components for maximum performance across a vast array of web-capable devices and browsers',
    ],
    requirements: [
      'Strong proficiency in JavaScript, including DOM manipulation and the JavaScript object model',
      'Thorough understanding of React.js and its core principles',
      'Experience with popular React.js workflows (such as Flux or Redux)',
      'Familiarity with modern front-end build pipelines and tools',
      'Experience with TypeScript is a plus',
    ],
    type: 'Full-time',
  },
  {
    id: 2,
    title: 'Backend Developer',
    company: 'DataStream Solutions',
    logo: 'https://picsum.photos/seed/DataStream/100/100',
    location: 'New York, NY',
    salary: '$130,000 - $170,000',
    description: 'DataStream Solutions is seeking a skilled Backend Developer to design, develop, and maintain our server-side logic and databases.',
    responsibilities: [
      'Design and implement robust APIs and microservices',
      'Manage hosting environments, including database administration and scaling applications to support load changes',
      'Integrate our various data storage solutions',
      'Implement security and data protection measures',
    ],
    requirements: [
      'Proven experience as a Backend Developer',
      'In-depth understanding of web development',
      'Experience with programming languages like Python, Java, or Node.js',
      'Familiarity with database technology such as MySQL, PostgreSQL, and MongoDB',
      'Excellent problem-solving skills',
    ],
    type: 'Full-time',
  },
  {
    id: 3,
    title: 'Product Manager Intern',
    company: 'Creative Minds',
    logo: 'https://picsum.photos/seed/Creative/100/100',
    location: 'Austin, TX (Remote)',
    salary: '$4,000 / month',
    description: 'Join our product team as an intern and help shape the future of our creative software suite. This is a great opportunity to learn and grow.',
    responsibilities: [
      'Conduct market research and competitive analysis',
      'Assist in defining product vision, roadmap, and growth opportunities',
      'Work closely with engineering, design, and marketing teams',
      'Gather and prioritize product and customer requirements',
    ],
    requirements: [
      'Currently pursuing a BS/BA or MS/MA in Computer Science, Business, or a related field',
      'Strong analytical and problem-solving skills',
      'Excellent communication and teamwork skills',
      'Passion for technology and product development',
    ],
    type: 'Internship',
  },
  {
    id: 4,
    title: 'UI/UX Designer',
    company: 'Pixel Perfect Co.',
    logo: 'https://picsum.photos/seed/Pixel/100/100',
    location: 'Chicago, IL',
    salary: '$90,000 - $110,000',
    description: 'We are on the hunt for a talented UI/UX Designer to create amazing user experiences. The ideal candidate should have an eye for clean and artful design.',
    responsibilities: [
      'Gather and evaluate user requirements in collaboration with product managers and engineers',
      'Illustrate design ideas using storyboards, process flows, and sitemaps',
      'Design graphic user interface elements, like menus, tabs, and widgets',
      'Develop UI mockups and prototypes that clearly illustrate how sites function and look',
    ],
    requirements: [
      'Proven work experience as a UI/UX Designer or similar role',
      'Portfolio of design projects',
      'Knowledge of wireframe tools (e.g. Wireframe.cc and InVision)',
      'Up-to-date knowledge of design software like Adobe Illustrator and Photoshop',
      'Team spirit; strong communication skills to collaborate with various stakeholders',
    ],
    type: 'Contract',
  },
  {
    id: 5,
    title: 'Data Scientist',
    company: 'QuantumLeap AI',
    logo: 'https://picsum.photos/seed/Quantum/100/100',
    location: 'Seattle, WA',
    salary: '$140,000 - $180,000',
    description: 'QuantumLeap AI is looking for a Data Scientist to analyze large amounts of raw information to find patterns that will help improve our company.',
    responsibilities: [
        'Identify valuable data sources and automate collection processes',
        'Undertake preprocessing of structured and unstructured data',
        'Analyze large amounts of information to discover trends and patterns',
        'Build predictive models and machine-learning algorithms',
        'Present information using data visualization techniques',
    ],
    requirements: [
        'Proven experience as a Data Scientist or Data Analyst',
        'Experience in data mining and machine learning',
        'Knowledge of Python, SQL and R',
        'Experience using business intelligence tools (e.g. Tableau) and data frameworks (e.g. Hadoop)',
        'Analytical mind and business acumen',
    ],
    type: 'Full-time',
  },
];

// Fix: Add USERS constant
export const USERS: User[] = [
  {
    id: 101,
    email: 'student@test.com',
    password: 'password',
    role: 'student',
    name: 'Alice Johnson',
    department: 'Computer Science & Engineering',
  },
  {
    id: 102,
    email: 'student2@test.com',
    password: 'password',
    role: 'student',
    name: 'Eve Adams',
    department: 'Electrical Engineering',
  },
  {
    id: 201,
    email: 'teacher@test.com',
    password: 'password',
    role: 'teacher',
    name: 'Prof. Bob Williams',
  },
  {
    id: 301,
    email: 'hod@test.com',
    password: 'password',
    role: 'hod',
    name: 'Dr. Charlie Brown',
  },
  {
    id: 401,
    email: 'pto@test.com',
    password: 'password',
    role: 'pto',
    name: 'Diana Prince',
  },
];
